name: Oxa-AntiCheat
version: 1.3.5
author: Aorux
main: fr.aorux.oxa.Main
depend: [ProtocolLib]
api-version: '1.20'
commands:
  oxa:
    description: Main command for Oxa AntiCheat
    usage: /oxa <subcommand>
    permission: oxa-anticheat.main
    subcommands:
      help:
        description: Help form Oxa AntiCheat
        usage: /oxa help
      reload:
        description: Reload Oxa AntiCheat
        usage: /oxa reload
      banip:
        description: Ban an adresse IP
        usage: /oxa banip
      unbanip:
        description: UnBan an adresse IP
        usage: /oxa unbanip
      openinv:
        description: Open inventory Player
        usage: /oxa openinv